name             'chef-tefenua-frontal'
maintainer       'stephane LII'
maintainer_email 'stephane.lii@informatique.gov.pf'
license          'All rights reserved'
description      'Installs/Configures chef-tefenua-frontal'
long_description 'Installs/Configures chef-tefenua-frontal'
version          '0.1.0'
depends 'apt'
